# Generated by Django 5.2.7 on 2025-11-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="заголовок", max_length=150, verbose_name="Заголовок")),
                ("content", models.TextField(help_text="содержимое", verbose_name="Содержимое")),
                ("image", models.ImageField(blank=True, null=True, upload_to="images/")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_published", models.BooleanField(default=False, verbose_name="Признак публикации")),
                ("views_counter", models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "запись",
                "verbose_name_plural": "записи",
                "ordering": ["-created_at"],
            },
        ),
    ]
