# Generated by Django 5.2.8 on 2025-11-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_publish_post", "Can publish post")],
                "verbose_name": "запись",
                "verbose_name_plural": "записи",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="publish_status",
            field=models.CharField(
                choices=[("DRAFT", "Черновик"), ("PUBLISH", "Публикуется"), ("SUBMIT", "На рассмотрение")],
                default="DRAFT",
                max_length=15,
                verbose_name="Подача на публикацию",
            ),
        ),
    ]
