# Generated by Django 5.2.7 on 2025-11-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_clientmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmessage",
            name="is_answered",
            field=models.BooleanField(default=False, verbose_name="Рассмотрено"),
        ),
    ]
