# Generated by Django 5.2.7 on 2025-11-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_clientmessage_is_answered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.category", verbose_name="Категория"
            ),
        ),
    ]
