# Generated by Django 5.2.8 on 2025-11-21 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_in_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="publication",
            field=models.CharField(
                choices=[("published", "Публикуется"), ("unpublished", "Не публикуется")],
                default="unpublished",
                max_length=15,
                verbose_name="Публикация",
            ),
        ),
    ]
