# Generated by Django 5.2.8 on 2025-11-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_product_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="owner",
        ),
    ]
