# Generated by Django 5.2.8 on 2025-11-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_remove_product_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="publication",
            field=models.BooleanField(default=False, verbose_name="Публикуется"),
        ),
    ]
